name: Android Library Build

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Update gradle-wrapper.properties
        run: |
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip" > gradle/wrapper/gradle-wrapper.properties

      - name: Display Gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew :library:assembleRelease --warning-mode all --info

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: library-release
          path: library/build/outputs/aar/library-release.aar

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download AAR
        uses: actions/download-artifact@v4
        with:
          name: library-release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: library-release.aar
          generate_release_notes: true